namespace AssignmentManagement.Domain.Common;

/// <summary>
/// Base class for all domain entities. Entities have identity: two entities of the
/// same type are equal when their identifiers match, regardless of any other state.
/// </summary>
public abstract class Entity : IEquatable<Entity>
{
    /// <summary>
    /// Unique identifier of the entity. Generated by the domain when the entity is
    /// created and persisted by the storage layer.
    /// </summary>
    public Guid Id { get; protected set; }

    /// <summary>
    /// Creates a new entity with a fresh identifier.
    /// </summary>
    protected Entity() => Id = Guid.NewGuid();

    /// <summary>
    /// Creates an entity with an explicit identifier (used by persistence when
    /// hydrating an existing record).
    /// </summary>
    protected Entity(Guid id) => Id = id;

    /// <inheritdoc />
    public bool Equals(Entity? other) =>
        other is not null && other.GetType() == GetType() && other.Id == Id;

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Entity);

    /// <inheritdoc />
    public override int GetHashCode() => HashCode.Combine(GetType(), Id);

    /// <summary>Compares two entities for structural identity equality.</summary>
    public static bool operator ==(Entity? left, Entity? right) =>
        left is null ? right is null : left.Equals(right);

    /// <summary>Compares two entities for structural identity inequality.</summary>
    public static bool operator !=(Entity? left, Entity? right) => !(left == right);
}
